### ISSUE TITLE
tcl REST library?

### ISSUE THREAD

**Issue by tfaoro** [jasonroman/eggdrop-slackbot#1]
Heya Jason,

Not really an issue with your code per se, but I could use your help here:

```
can't find package rest
   while executing
"package require rest"
```

What do I need to install on a Ubuntu system in order to get tcl to find this library? I tried tcl8.5-dev without success...

**Comment by jasonroman** [comment]
Hello,

You'll need the tcllib library installed which includes this package.  More details about downloading and installing can be found here:  http://core.tcl.tk/tcllib/doc/trunk/embedded/index.html
